
public class Domicilio {
    private String calle;
        private int numero;

            public Domicilio(String calle, int numero) {
                    if (calle != null && !calle.trim().isEmpty()) {
                                this.calle = calle;
                                        }

                                                if (numero > 0) {
                                                            this.numero = numero;
                                                                    }
                                                                        }

                                                                            public boolean esCompleto() {
                                                                                    if (!calle.isEmpty() && numero > 0)
                                                                                            return true;
                                                                                                    else
                                                                                                                    return false;
                                                                                                                        }

                                                                                                                            @Override
                                                                                                                                public String toString() {
                                                                                                                                        return calle + " " + numero;
                                                                                                                                            }
                                                                                                                                            }

                                                                                                                                            ```
                                                                                                                                            ```

                                                                                                                                            public class Persona {
                                                                                                                                                private String nombre;
                                                                                                                                                    private int edad;
                                                                                                                                                        private String dni;
                                                                                                                                                            private char sexo;
                                                                                                                                                                private double peso;
                                                                                                                                                                    private double altura;
                                                                                                                                                                        private Domicilio domicilio; // ¡Aquí el atributo complejo! Inicialícenlo en constructores

                                                                                                                                                                            // Constructor con nombre (solo asigna nombre, el resto por defecto de Java)
                                                                                                                                                                                public Persona(String nombre) {
                                                                                                                                                                                        if (nombre != null && !nombre.trim().isEmpty()) {
                                                                                                                                                                                                    this.nombre = nombre;
                                                                                                                                                                                                            }
                                                                                                                                                                                                                    this.domicilio = new Domicilio("", 0); // Inicializa el objeto complejo con valores por defecto
                                                                                                                                                                                                                        }

                                                                                                                                                                                                                            // Constructor completo
                                                                                                                                                                                                                                public Persona(String nombre, int edad, String dni, char sexo, double peso, double altura, Domicilio domicilio) {
                                                                                                                                                                                                                                        if (nombre != null && !nombre.trim().isEmpty()) {
                                                                                                                                                                                                                                                    this.nombre = nombre;
                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                    if (edad >= 0) {
                                                                                                                                                                                                                                                                                this.edad = edad;
                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                if (dni != null && !dni.trim().isEmpty()) {
                                                                                                                                                                                                                                                                                                            this.dni = dni;
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                            if (comprobarSexo(sexo)) {
                                                                                                                                                                                                                                                                                                                                        this.sexo = sexo;
                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                        if (peso >= 0) {
                                                                                                                                                                                                                                                                                                                                                                    this.peso = peso;
                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                    if (altura >= 0) {
                                                                                                                                                                                                                                                                                                                                                                                                this.altura = altura;
                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                this.domicilio = domicilio; // Asigna el objeto complejo
                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                        // Método esMayorDeEdad
                                                                                                                                                                                                                                                                                                                                                                                                                            public boolean esMayorDeEdad() {
                                                                                                                                                                                                                                                                                                                                                                                                                                    return edad >= 18; //avanzado pero lo dejo para que sus cerebros se activen 
                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                            // Método privado para validar sexo
                                                                                                                                                                                                                                                                                                                                                                                                                                                private boolean comprobarSexo(char sexo) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        //completar
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                // toString
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public String toString() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return "Persona [nombre=" + nombre + ", edad=" + edad + ", DNI=" + dni +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ", sexo=" + sexo + ", peso=" + peso + ", altura=" + altura + ", domicilio=" + domicilio + "]";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          public String infoDomicilio() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return "Domicilio de " + nombre + ": " + domicilio + ". ¿Completo? " + domicilio.esCompleto();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ```
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ```

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      public class TestPersona {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          public static void main(String[] args) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Domicilio dom1 = new Domicilio("Av. Rivadavia", 1234);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Persona p1 = new Persona("Laura", 20, "12345678", 'M', 60.5, 1.65, dom1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  System.out.println(p1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          System.out.println(p1.infoDomicilio());

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Persona p2 = new Persona("Pedro");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          System.out.println(p2); // Domicilio por defecto
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ```